<?php

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_sagepay_paypal_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_sagepay_paypal'] = array(
    'base' => 'commerce_sagepay_paypal',
    'title' => t('SagePay PayPal Integration'),
    'display_title' => t('PayPal'),
    'short_title' => t('PayPal'),
    'description' => t('Integration with PayPal using Sage Pay Direct.'),
    'active' => FALSE,
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
    'callbacks' => array(),
    'file' => 'includes/commerce_sagepay_paypal.inc',
  );
  return $payment_methods;
}

/**
 * Implements hook_menu().
 */
function commerce_sagepay_paypal_menu() {
  $items = array();

  // Define a path to receive PayPal Callback).
  $items['commerce-sagepay/paypal-callback/%'] = array(
    'page callback' => 'commerce_sagepay_paypal_handle_callback',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_sagepay_paypal.inc',
  );

  return $items;
}

